Pull image digest directly from the Docker.io API to deal better when there's no connectivity

diff --git a/bin/pwnmake b/bin/pwnmake
--- a/bin/pwnmake
+++ b/bin/pwnmake
@@ -22,7 +22,8 @@ realpath() (
 
 show_help() {
 	cat <<EOF
-Usage: pwnmake [--reinit] [--shell] [--dir <path>] [--tag <tag>] [--digest <digest>] [--] [targets...]
+Usage: pwnmake [--reinit] [--shell] [--dir <path>] [--tag <tag>] [--digest <digest>]
+               [--skip-update] [--] [targets...]
 Options:
   --reinit           Force the builder container to be reinitialized
   --shell            Enter an interactive shell in the builder container (for debugging)
@@ -32,6 +33,7 @@ Options:
                      '${docker_image_prefix}2.0' as the builder image base.
   --digest <digest>  PwnableHarness builder image digest to use. For example, '--digest sha256:abc...123'
                      will use '${docker_image_repo}@sha256:abc...123' as the builder image base.
+  --skip-update      Don't attempt to ensure the builder image is up-to-date.
   --                 Stop parsing options and pass all further arguments to 'make'.
   targets...         Arguments to be passed to 'make'. These can be targets to build or options like '-j8'.
 Example: pwnmake -j4 docker-start publish VERBOSE=1
@@ -42,9 +44,24 @@ docker_image_exists() {
 	docker image inspect "$1" >/dev/null 2>&1
 }
 
-docker_get_remote_digest() {
-	docker buildx imagetools inspect --format '{{printf "%s\n" .Manifest.Digest}}' "$1"
-}
+docker_get_remote_digest() (
+	image=${1%:*}
+	tag=${1#$image:}
+	
+	# Use curl and sed to avoid unnecessary dependencies. Hooray for parsing JSON
+	# with sed instead of jq to improve user installation experience! /s
+	token=$(curl --silent "https://auth.docker.io/token?scope=repository:$image:pull&service=registry.docker.io" \
+		| sed 's/^.*"token":"\([^"]*\)".*$/\1/'
+	)
+	if [ -z "$token" ]; then
+		echo "Error while trying to authenticate with the Docker.io API" >&2
+		exit 1
+	fi
+	
+	curl -sSL -D - -o /dev/null -H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
+			-H "Authorization: Bearer ${token}" "https://registry-1.docker.io/v2/$image/manifests/$tag" \
+		| grep -ie '^docker-content-digest:' | cut -d ' ' -f 2- | tr -d '\r'
+)
 
 docker_get_local_digest() {
 	docker image inspect --format '{{index .RepoDigests 0}}' "$1" 2>/dev/null | cut -d '@' -f 2
@@ -57,6 +74,7 @@ main() {
 	reinit=
 	shell=
 	digest=
+	skip_update=
 	
 	while [ "$#" -gt 0 ]; do
 		case "$1" in
@@ -91,6 +109,11 @@ main() {
 				shift
 				digest=$1
 				shift
+				;;
+			
+			--skip-update)
+				shift
+				skip_update=1
 				;;
 			
 			--)
@@ -131,27 +154,34 @@ main() {
 	need_pull=
 	if [ "$tag" = "latest" ]; then
 		# For the "latest" tag, check if the local digest (if present) matches the remote one
-		remote_digest=$(docker_get_remote_digest "$docker_image")
 		local_digest=$(docker_get_local_digest "$docker_image")
-		
 		if [ -z "$local_digest" ]; then
-			echo "Pulling builder image for the first time..."
+			echo "Pulling builder image for the first time..." >&2
 			need_pull=1
-		elif [ "$local_digest" != "$remote_digest" ]; then
-			echo "Pulling newer version of the builder image..."
-			need_pull=1
+		elif [ "$skip_update" != "1" ]; then
+			remote_digest=$(docker_get_remote_digest "$docker_image")
+			if [ -z "$remote_digest" ]; then
+				echo "Unable to read remote image digest, skipping update" >&2
+			elif [ "$local_digest" != "$remote_digest" ]; then
+				echo "Pulling newer version of the builder image..." >&2
+				need_pull=1
+			fi
 		fi
 	else
 		# For tags other than "latest", just ensure that the tag is present locally. It's assumed
 		# that only the "latest" tag is movable.
 		if ! docker_image_exists "$docker_image"; then
-			echo "Pulling builder image at tag $tag..."
+			echo "Pulling builder image at tag $tag..." >&2
 			need_pull=1
 		fi
 	fi
 	
+	# Unconditionally running docker pull would work, but then there would be either
+	# unexplained long delays when trying to run pwnmake (because an image is being
+	# pulled) or unnecessarily verbose output from docker pull even when the image
+	# is up to date. By doing the above checks, we can make the user experience better.
 	if [ "$need_pull" = "1" ]; then
-		docker pull "$docker_image"
+		docker pull "$docker_image" >&2
 	fi
 	
 	# A hash is built from:
