Add support for changing base images (#27)
Projects can now define `UBUNTU_VERSION` to any version of Ubuntu that is desired (supporting both numerical versions like `16.04` and named aliases like `focal`). This will be used as the Ubuntu version for compilers and for the runtime container.

Internally, there's a big change to the various Docker images and containers managed by PwnableHarness. Here's the current overview:

* `pwnmake-v<pwnmake version>`: This is an Ubuntu 24.04 image used to run `make` commands, and is invoked by the `pwnmake` CLI script.
* `pwncc-<ubuntu version>-v<pwnableharness-version>`: These are a collection of tiny Ubuntu images with compilers installed. Any compiler or linker invocations used to build challenges are now run through these `pwncc` containers, to easily allow compiling for specific Ubuntu versions.
* `base-<ubuntu version>-v<pwnableharness-version>`: These are a collection of Ubuntu images that serve as the base runtime environment for PwnableHarness challenges. They contain `libpwnableharness*.so` and `pwnableserver` and have the environment set up, ready to serve a challenge.

From a usage perspective, the only change is the new `UBUNTU_VERSION` variable. Compilation commands will be somewhat slower due to now running each one in a separate Docker container, but that's an acceptable trade-off since PwnableHarness projects are typically small.

diff --git a/bin/pwnmake b/bin/pwnmake
--- a/bin/pwnmake
+++ b/bin/pwnmake
@@ -1,42 +1,135 @@
-#!/bin/sh
+#!/bin/bash
+set -euo pipefail
 
-# Keep aligned with PWNABLEHARNESS_VERSION in Makefile
-version=2.0b1
+# Keep aligned with /VERSION
+version=${PWNMAKE_VERSION:-2.1}
+
+# This is the lowest version of pwnmake image that is supported by this pwnmake script
+PWNABLEHARNESS_VERSION_MIN=2.1
 
 docker_image_repo=c0deh4cker/pwnableharness
-docker_image_tag_prefix=builder-
+docker_image_tag_prefix=pwnmake-
 docker_image_prefix=$docker_image_repo:$docker_image_tag_prefix
 
+# There's no arm64 version available, so only try pulling the amd64 version
+export DOCKER_DEFAULT_PLATFORM=linux/amd64
+
+
+# https://stackoverflow.com/a/4025065
+_vercmp() {
+	if [[ $1 == $2 ]]
+	then
+		return 0
+	fi
+	local IFS=.
+	local i ver1=($1) ver2=($2)
+	# fill empty fields in ver1 with zeros
+	for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
+	do
+		ver1[i]=0
+	done
+	for ((i=0; i<${#ver1[@]}; i++))
+	do
+		if ((10#${ver1[i]:=0} > 10#${ver2[i]:=0}))
+		then
+			return 1
+		fi
+		if ((10#${ver1[i]} < 10#${ver2[i]}))
+		then
+			return 2
+		fi
+	done
+	return 0
+}
+
+vercmp() {
+	_vercmp "$1" "$3"
+	case $? in
+	0)
+		case "$2" in
+			"=="|"<="|">="|"-eq"|"-le"|"-ge") return 0;;
+		esac
+		;;
+	1)
+		case "$2" in
+			">"|">="|"-gt"|"-ge") return 0;;
+		esac
+		;;
+	2)
+		case "$2" in
+			"<"|"<="|"-lt"|"-le") return 0;;
+		esac
+		;;
+	esac
+	
+	return 1
+}
 
 # https://stackoverflow.com/a/18443300
 realpath() (
-	OURPWD=$PWD
+	local OURPWD="$PWD"
 	cd "$(dirname "$1")"
-	LINK=$(readlink "$(basename "$1")")
+	local LINK="$(readlink "$(basename "$1")")"
 	while [ "$LINK" ]; do
 		cd "$(dirname "$LINK")"
-		LINK=$(readlink "$(basename "$1")")
+		LINK="$(readlink "$(basename "$1")")"
 	done
-	REALPATH="$PWD/$(basename "$1")"
+	local REALPATH="$PWD/$(basename "$1")"
 	cd "$OURPWD"
 	echo "$REALPATH"
 )
 
+docker_image_exists() {
+	docker image inspect "$1" >/dev/null 2>&1
+}
+
+docker_get_remote_digest() (
+	local image="${1%:*}"
+	local tag="${1#$image:}"
+	
+	# Use curl and sed to avoid unnecessary dependencies. Hooray for parsing JSON
+	# with sed instead of jq to improve user installation experience! /s
+	local token=$(curl --silent "https://auth.docker.io/token?scope=repository:$image:pull&service=registry.docker.io" \
+		| sed 's/^.*"token":"\([^"]*\)".*$/\1/'
+	)
+	if [ -z "$token" ]; then
+		echo "Error while trying to authenticate with the Docker.io API" >&2
+		exit 1
+	fi
+	
+	curl -sSL -D - -o /dev/null \
+			-H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
+			-H "Authorization: Bearer ${token}" \
+			"https://registry-1.docker.io/v2/$image/manifests/$tag" \
+		| grep -ie '^docker-content-digest:' | cut -d ' ' -f 2- | tr -d '\r'
+)
+
+docker_get_local_digest() {
+	docker image inspect --format '{{index .RepoDigests 0}}' "$1" 2>/dev/null | cut -d '@' -f 2
+}
+
 
 show_help() {
 	cat <<EOF
-Usage: pwnmake [-C/--dir <path>] [--tag <tag>] [--digest <digest>] [--skip-update]
-               [--reinit] [--shell] [--help] [--version] [--] [targets...]
+Usage: pwnmake [-C/--dir <path>] [--env <NAME=VALUE> ...] [--pwnableharness-version <version>]
+               [--tag <tag>] [--digest <digest>] [--skip-update] [--reinit] [--shell] [--help] [--version]
+               [--] [targets...]
 Options:
   -C, --dir <path>   Path to the directory to use as a PwnableHarness workspace (default '.')
-  --tag <tag>        PwnableHarness builder image tag to use (default 'latest'). The tag will be
-                     prefixed with '${docker_image_tag_prefix}'. For example, '--tag 2.0' will use
-                     '${docker_image_prefix}2.0' as the builder image base.
-  --digest <digest>  PwnableHarness builder image digest to use. For example, '--digest sha256:abc...123'
-                     will use '${docker_image_repo}@sha256:abc...123' as the builder image base.
-  --skip-update      Don't attempt to ensure the builder image is up-to-date.
-  --reinit           Force the builder container to be reinitialized
-  --shell            Enter an interactive shell in the builder container (for debugging)
+  --env <NAME=VALUE> Set an environment variable within the pwnmake image for this command.
+  --pwnableharness-version <version>
+                     Select a specific PwnableHarness version for the pwnmake image base. For example,
+                     '--pwnableharness-version 2.1' will use '${docker_image_tag_prefix}-v2.1' as the
+                     pwnmake image base.
+  --tag <tag>        PwnableHarness pwnmake image tag to use (default 'latest'). The tag will be
+                     prefixed with '${docker_image_tag_prefix}'. For example, '--tag v2.1' will use
+                     '${docker_image_tag_prefix}v2.1' as the pwnmake image base.
+  --digest <digest>  PwnableHarness pwnmake image digest to use. For example, '--digest sha256:abc...123'
+                     will use '${docker_image_repo}@sha256:abc...123' as the pwnmake image base.
+  --skip-update      Don't attempt to ensure the pwnmake image is up-to-date.
+  --reinit           Force the pwnmake container to be reinitialized
+  --shell            Enter an interactive shell in the pwnmake container (for debugging)
+  --verbose          Show executed commands verbosely (for debugging)
   --help             Display this help message.
   --version          Display the version of the pwnmake script.
   --                 Stop parsing options and pass all further arguments to 'make'.
@@ -45,41 +138,16 @@ Example: pwnmake -j4 docker-start publish VERBOSE=1
 EOF
 }
 
-docker_image_exists() {
-	docker image inspect "$1" >/dev/null 2>&1
-}
-
-docker_get_remote_digest() (
-	image=${1%:*}
-	tag=${1#$image:}
-	
-	# Use curl and sed to avoid unnecessary dependencies. Hooray for parsing JSON
-	# with sed instead of jq to improve user installation experience! /s
-	token=$(curl --silent "https://auth.docker.io/token?scope=repository:$image:pull&service=registry.docker.io" \
-		| sed 's/^.*"token":"\([^"]*\)".*$/\1/'
-	)
-	if [ -z "$token" ]; then
-		echo "Error while trying to authenticate with the Docker.io API" >&2
-		exit 1
-	fi
-	
-	curl -sSL -D - -o /dev/null -H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
-			-H "Authorization: Bearer ${token}" "https://registry-1.docker.io/v2/$image/manifests/$tag" \
-		| grep -ie '^docker-content-digest:' | cut -d ' ' -f 2- | tr -d '\r'
-)
-
-docker_get_local_digest() {
-	docker image inspect --format '{{index .RepoDigests 0}}' "$1" 2>/dev/null | cut -d '@' -f 2
-}
 
 # pwnmake [...]
 main() {
-	workspace=.
-	tag=latest
-	reinit=
-	shell=
-	digest=
-	skip_update=
+	local workspace=.
+	local reinit shell skip_update digest tag verbose
+	local ph_version="${PWNMAKE_PWNABLEHARNESS_VERSION:-latest}"
+	local env_args=()
+	
+	test -n "${PWNMAKE_TAG:-}" && tag="$PWNMAKE_TAG"
+	test -n "${PWNMAKE_DIGEST:-}" && digest="$PWNMAKE_DIGEST"
 	
 	while [ "$#" -gt 0 ]; do
 		case "$1" in
@@ -98,21 +166,38 @@ main() {
 				shell=1
 				;;
 			
+			--verbose)
+				shift
+				verbose=1
+				;;
+			
 			-C|--dir)
 				shift
-				workspace=$1
+				workspace="$1"
+				shift
+				;;
+			
+			--env)
+				shift
+				env_args+=(--env "$2")
+				shift
+				;;
+			
+			--pwnableharness-version)
+				shift
+				ph_version="$1"
 				shift
 				;;
 			
 			--tag)
 				shift
-				tag=$1
+				tag="$1"
 				shift
 				;;
 			
 			--digest)
 				shift
-				digest=$1
+				digest="$1"
 				shift
 				;;
 			
@@ -137,6 +222,37 @@ main() {
 		esac
 	done
 	
+	if [ -n "$verbose" ]; then
+		set -x
+	fi
+	
+	local HOST_WORKSPACE=$(realpath "$workspace")
+	
+	# Check that --pwnableharness-version is a supported version
+	if [ -n "$ph_version" ] && [ "$ph_version" != "latest" ]; then
+		if vercmp "$ph_version" -lt "$PWNABLEHARNESS_VERSION_MIN"; then
+			echo "PwnableHarness version $ph_version is unsupported; must be >=$PWNABLEHARNESS_VERSION_MIN" >&2
+			exit 1
+		fi
+	fi
+	
+	# Check that --tag references a supported tag
+	if [ -n "$tag" ] && [ "$tag" != "latest" ]; then
+		if vercmp "${tag#v}" -lt "$PWNABLEHARNESS_VERSION_MIN"; then
+			echo "pwnmake image with tag $tag is unsupported; must be >=$PWNABLEHARNESS_VERSION_MIN" >&2
+			exit 1
+		fi
+	fi
+	
+	# Build tag if neither a tag/digest were supplied
+	if [ -z "$tag" ] && [ -z "$digest" ]; then
+		tag="$ph_version"
+		if [ "$ph_version" != "latest" ]; then
+			tag="v$ph_version"
+		fi
+	fi
+	
+	local docker_image
 	if [ -n "$digest" ]; then
 		# With a digest, the tag is unnecessary. It can be useful as documentation, though,
 		# as it shows up in 'docker ps'. If a tag was provided, include it.
@@ -151,7 +267,7 @@ main() {
 	
 	# Get version of the Docker server on the host to know which version of the
 	# Docker CLI to install in the builder container.
-	DOCKER_VERSION=$(docker version --format '{{.Server.Version}}')
+	local DOCKER_VERSION="$(docker version --format '{{.Server.Version}}' | cut -d- -f1)"
 	if [ "$?" != 0 ]; then
 		echo "Docker must be installed!" >&2
 		exit 1
@@ -161,19 +277,18 @@ main() {
 	docker volume create pwnmake-docker-cli >/dev/null 2>&1 || true
 	
 	# Attempt to determine if a docker pull is necessary
-	need_pull=
+	local need_pull=
 	if [ -z "$digest" ] && [ "$tag" = "latest" ]; then
 		# For the "latest" tag, check if the local digest (if present) matches the remote one
-		local_digest=$(docker_get_local_digest "$docker_image")
-		if [ -z "$local_digest" ]; then
-			echo "Pulling builder image for the first time..." >&2
+		if ! local_digest="$(docker_get_local_digest "$docker_image")"; then
+			echo "Pulling pwnmake image for the first time..." >&2
 			need_pull=1
 		elif [ "$skip_update" != "1" ]; then
-			remote_digest=$(docker_get_remote_digest "$docker_image")
+			local remote_digest="$(docker_get_remote_digest "$docker_image")"
 			if [ -z "$remote_digest" ]; then
 				echo "Unable to read remote image digest, skipping update" >&2
 			elif [ "$local_digest" != "$remote_digest" ]; then
-				echo "Pulling newer version of the builder image..." >&2
+				echo "Pulling newer version of the pwnmake image..." >&2
 				need_pull=1
 			fi
 		fi
@@ -181,7 +296,7 @@ main() {
 		# For tags other than "latest", just ensure that the tag is present locally. It's assumed
 		# that only the "latest" tag is movable.
 		if ! docker_image_exists "$docker_image"; then
-			echo "Pulling builder image ${docker_image}..." >&2
+			echo "Pulling pwnmake image ${docker_image}..." >&2
 			need_pull=1
 		fi
 	fi
@@ -196,24 +311,36 @@ main() {
 	
 	# A hash is built from:
 	# * Current version of the pwnmake script
-	# * The digest of the pwnableharness builder image (pre-initialization)
+	# * The pwnableharness pwnmake image ID (pre-initialization)
 	# * The hashes of all prebuild scripts
 	# This is done so that if the pwnmake script, base image, or any prebuild scripts
-	# change, the builder image will be reinitialized.
-	builder_digest=$(docker_get_local_digest "$docker_image")
-	prebuild_hash=$(find "$workspace" -name prebuild.sh -print0 | sort -z | xargs -0 -n1 -r shasum -a 256 | shasum -a 256 | awk '{print $1}')
-	pwnmake_tag=$(echo "$version;$builder_digest;$prebuild_hash" | shasum -a 256 | head -c 12)
-	pwnmake_repo=c0deh4cker/pwnmake
-	pwnmake_image=$pwnmake_repo:$pwnmake_tag
-	pwnmake_container=pwnmake-$pwnmake_tag
+	# change, the pwnmake image will be reinitialized.
+	local image_id=$(docker image inspect --format '{{.Id}}' "$docker_image")
+	local prebuild_hash=$(find "$workspace" -name prebuild.sh -print0 | sort -z | xargs -0 -n1 -r shasum -a 256 | shasum -a 256 | awk '{print $1}')
+	local pwnmake_tag=$(echo "$version;$image_id;$prebuild_hash" | shasum -a 256 | head -c 12)
+	
+	# This is intentionally not "c0deh4cker/pwnableharness", which is the real
+	# remote image repo on Docker Hub. Here, "c0deh4cker/pwnmake" is only used
+	# for locally-generated builder images based on a pwnmake image from the
+	# real remote.
+	local pwnmake_repo=c0deh4cker/pwnmake
+	local pwnmake_image=$pwnmake_repo:$pwnmake_tag
+	local pwnmake_container=pwnmake-$pwnmake_tag
 	
 	# To force reinitialization, delete the pwnmake image
 	if [ "$reinit" = "1" ]; then
-		# Remove any old pwnmake images
+		# Remove any old pwnmake images. Note that this may remove pwnmake
+		# images used by other project directories that `pwnmake` has been run
+		# from. This is acceptable, as they will be recreated on-demand. I'd
+		# rather not force users to clean up their old pwnmake images. Rather,
+		# they shouldn't even need to really know about or worry about the
+		# pwnmake images.
 		docker image rm $(docker image ls -q "$pwnmake_repo") >/dev/null 2>&1 || true
 	fi
 	
-	host_os=$(uname -s)
+	local env_arg_sock_chmod=
+	local host_os=$(uname -s)
+	local DOCKER_GID host_docker_sock
 	if [ "$host_os" = "Darwin" ]; then
 		# https://github.com/docker/for-mac/issues/4755
 		# Because of the above issue, /var/run/docker.sock on Docker for Mac is
@@ -239,58 +366,69 @@ main() {
 	fi
 	
 	if ! docker_image_exists "$pwnmake_image"; then
-		# Remove any old pwnmake images
+		# Remove any old pwnmake containers and images
+		docker container rm $(docker container ls -a --format '{{.ID}} {{.Names}}' | grep 'pwnmake-' | awk '{ print $1 }') >/dev/null 2>&1 || true
 		docker image rm $(docker image ls -q "$pwnmake_repo") >/dev/null 2>&1 || true
 		
 		# Get the current user's UID and GID so that any files created by the builder
 		# container will have proper ownership.
-		CALLER_UID=$(id -u)
-		CALLER_GID=$(id -g)
+		local CALLER_UID=$(id -u)
+		local CALLER_GID=$(id -g)
 		
 		# Run the builder initialization and prep scripts then save as a new image
-		docker run \
+		if docker run \
 			--name "$pwnmake_container" \
-			--env PWNMAKE_VERSION="$version" \
-			--env BUILDER_INIT=1 \
 			--env DOCKER_VERSION="$DOCKER_VERSION" \
+			--env HOST_WORKSPACE="$HOST_WORKSPACE" \
+			--env PWNMAKE_VERSION="$version" \
+			--env PWNMAKE_INIT=1 \
 			--env CALLER_UID="$CALLER_UID" \
 			--env CALLER_GID="$CALLER_GID" \
 			--env DOCKER_GID="$DOCKER_GID" \
+			-v "$HOST_WORKSPACE":/PwnableHarness/workspace \
 			-v "$host_docker_sock":/var/run/docker.sock \
 			-v pwnmake-docker-cli:/docker-cli \
-			-v "$(realpath $workspace)":/PwnableHarness/workspace \
-			-it "$docker_image" \
-		&& docker commit "$pwnmake_container" "$pwnmake_image" >/dev/null \
-		&& docker rm "$pwnmake_container" >/dev/null
+			-it "$docker_image"
+		then
+			docker commit "$pwnmake_container" "$pwnmake_image" >/dev/null
+			docker rm "$pwnmake_container" >/dev/null
+		else
+			ret=$?
+			docker rm "$pwnmake_container" >/dev/null
+			exit $ret
+		fi
+	fi
+	
+	local cmd_args
+	if [ "$shell" = "1" ]; then
+		if [ "$#" -gt 0 ]; then
+			cmd_args=(/bin/bash -c "$*")
+		else
+			cmd_args=(/bin/bash)
+			echo "Entering shell in builder container. To attempt the build normally, run:" >&2
+			echo "" >&2
+			echo "    pwnmake [args for make...]" >&2
+			echo "" >&2
+		fi
+	else
+		cmd_args=(/usr/bin/pwnmake "$@")
 	fi
 	
 	# The container is created and then thrown away with each command
-	if [ "$shell" = "1" ]; then
-		echo "Entering shell in builder container. To attempt the build normally, run:" >&2
-		echo "" >&2
-		echo "    /PwnableHarness/builder-entrypoint.sh [args for make...]" >&2
-		echo "" >&2
-		docker run \
-			--rm \
-			--env PWNMAKE_VERSION="$version" \
-			--env BUILDER_INIT=0 \
-			--env DOCKER_VERSION="$DOCKER_VERSION" \
-			-v "$host_docker_sock":/var/run/docker.sock \
-			-v pwnmake-docker-cli:/docker-cli \
-			-v "$(realpath $workspace)":/PwnableHarness/workspace \
-			--entrypoint /bin/bash \
-			-it "$pwnmake_image"
-	else
-		docker run \
-			--rm \
-			--env PWNMAKE_VERSION="$version" \
-			--env BUILDER_INIT=0 \
-			--env DOCKER_VERSION="$DOCKER_VERSION" \
-			-v "$host_docker_sock":/var/run/docker.sock \
-			-v pwnmake-docker-cli:/docker-cli \
-			-v "$(realpath $workspace)":/PwnableHarness/workspace \
-			-it "$pwnmake_image" "$@"
-	fi
+	docker run \
+		--rm \
+		--init \
+		--env DOCKER_VERSION="$DOCKER_VERSION" \
+		--env HOST_WORKSPACE="$HOST_WORKSPACE" \
+		--env PWNMAKE_VERSION="$version" \
+		--env PWNMAKE_INIT=0 \
+		${env_args[@]+"${env_args[@]}"} \
+		-v "$HOST_WORKSPACE":/PwnableHarness/workspace \
+		-v "$host_docker_sock":/var/run/docker.sock \
+		-v pwnmake-docker-cli:/docker-cli \
+		-it "$pwnmake_image" \
+		${cmd_args[@]+"${cmd_args[@]}"}
+		# cmd_args trick from https://stackoverflow.com/a/7577209
 }
 
 main "$@"
